kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodeploy
spec:
  replicas: 2
  minReadySeconds: 10 # wait for 45 sec before going to deploy next pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
      maxSurge: 1        # max number of pods to run for the deployment
  selector:
    matchLabels:
      lname: mongodb
  template:
    metadata:
      name: mongopod
      labels:
        lname: mongodb
    spec:
      containers:
       - name: mongocontainer
         image: mongo
         env:
         - name: MONGO_ROOT_PASSWORD
           value: yourpasword 
         - name: MONGO_USR 
           value: user 
         - name: MONGO_PASSWORD 
           value: user_pass 
         - name: MONGO_DATABASE 
           value: mongo 
           
      volumeMounts:
        - name: mongovol
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongovol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi   
---
kind: Service
apiVersion: v1
metadata:
   name: mongoservice
spec:
  clusterIp: None
  ports:
    - port: 27017
      targetPort: 27017
  selector: 
    lname: mongodb
